[build]
builder = "NIXPACKS"
buildCommand = "chmod +x ./gradlew && ./gradlew clean build -x test"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar build/libs/HangoutApp-1.0.0.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
